package projectstart;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import backEnd.*;

public class EmployeeProfile extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeProfile
     */
    EmployeeDashboard empD = new EmployeeDashboard();
    String EmpID;

    public EmployeeProfile() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField9 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        BtnDashboard = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtPhone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDesignation = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        BtnDashboard1 = new javax.swing.JButton();
        txtQualification = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtEID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Salary = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        Salary1 = new javax.swing.JLabel();
        txtLeaves = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel2.setText("Employee ID");
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel3.setText("Age");
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 50));

        BtnDashboard.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnDashboard.setText("Dashboard");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel4.setText("Phone");
        jLabel4.setMinimumSize(new java.awt.Dimension(50, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel5.setText("Department");
        jLabel5.setMinimumSize(new java.awt.Dimension(50, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel6.setText("Qualification");
        jLabel6.setMinimumSize(new java.awt.Dimension(50, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel7.setText("Designation");
        jLabel7.setMinimumSize(new java.awt.Dimension(50, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Update Data");

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel1.setText("Name");
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(592, 814));

        jPanel1.setBackground(new java.awt.Color(98, 99, 101));
        jPanel1.setLayout(null);

        txtPhone.setFocusable(false);
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhone);
        txtPhone.setBounds(330, 420, 160, 35);

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setText("Name");
        jLabel8.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 310, 106, 36);

        txtDesignation.setFocusable(false);
        txtDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesignationActionPerformed(evt);
            }
        });
        jPanel1.add(txtDesignation);
        txtDesignation.setBounds(330, 580, 160, 35);

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 51));
        jLabel9.setText("Age");
        jLabel9.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(130, 370, 106, 35);

        txtDepartment.setFocusable(false);
        txtDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartmentActionPerformed(evt);
            }
        });
        jPanel1.add(txtDepartment);
        txtDepartment.setBounds(330, 480, 160, 35);

        BtnDashboard1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnDashboard1.setForeground(new java.awt.Color(51, 0, 51));
        BtnDashboard1.setText("Dashboard");
        BtnDashboard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDashboard1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDashboard1);
        BtnDashboard1.setBounds(240, 730, 138, 38);

        txtQualification.setFocusable(false);
        txtQualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQualificationActionPerformed(evt);
            }
        });
        jPanel1.add(txtQualification);
        txtQualification.setBounds(330, 530, 160, 35);

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 51));
        jLabel10.setText("Phone");
        jLabel10.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(130, 420, 109, 35);

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 51));
        jLabel11.setText("Department");
        jLabel11.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(130, 480, 109, 35);

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 51));
        jLabel12.setText("Qualification");
        jLabel12.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(130, 530, 109, 33);

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 51));
        jLabel13.setText("Designation");
        jLabel13.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(130, 580, 101, 35);

        txtEID.setFocusable(false);
        txtEID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtEID);
        txtEID.setBounds(330, 260, 160, 35);

        txtName.setFocusable(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName);
        txtName.setBounds(330, 310, 160, 35);

        txtAge.setFocusable(false);
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge);
        txtAge.setBounds(330, 370, 160, 35);

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 51));
        jLabel14.setText("Employee ID");
        jLabel14.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(130, 250, 106, 35);

        Salary.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Salary.setForeground(new java.awt.Color(51, 0, 51));
        Salary.setText("Salary");
        Salary.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(Salary);
        Salary.setBounds(130, 630, 101, 35);

        txtSalary.setFocusable(false);
        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });
        jPanel1.add(txtSalary);
        txtSalary.setBounds(330, 640, 160, 35);

        Salary1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Salary1.setForeground(new java.awt.Color(51, 0, 51));
        Salary1.setText("Available Leaves");
        Salary1.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(Salary1);
        Salary1.setBounds(130, 690, 153, 35);

        txtLeaves.setFocusable(false);
        txtLeaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLeavesActionPerformed(evt);
            }
        });
        jPanel1.add(txtLeaves);
        txtLeaves.setBounds(330, 690, 160, 35);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EmpDash.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(243, 6, 139, 179);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 51));
        jLabel16.setText("     EMPLOYEE DASHBOARD");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(161, 197, 319, 65);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesignationActionPerformed

    private void txtDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartmentActionPerformed

    private void BtnDashboard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDashboard1ActionPerformed
        EmployeeDashboard empd = new EmployeeDashboard();
        empd.setVisible(true);
        empd.EmpID = this.EmpID;
        this.dispose();
    }//GEN-LAST:event_BtnDashboard1ActionPerformed

    public void displayInfo() {
        EmployeeOperations Op = new EmployeeOperations();
        txtEID.setText(EmpID);
        boolean b;
        int id = Integer.parseInt(txtEID.getText());
        try {
            b = Op.fetchUser(id);
            if (b) {
                txtName.setText(Op.Name);
                txtAge.setText(Op.Age);
                txtPhone.setText(Op.Phone);
                txtDepartment.setText(Op.Dept);
                txtQualification.setText(Op.Qual);
                txtDesignation.setText(Op.Desg);
                txtSalary.setText(Op.Salary.toString());
                txtLeaves.setText(Integer.toString(Op.AvLeaves));
            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        } catch (Exception ex) {
            Logger.getLogger(EditProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void txtQualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualificationActionPerformed

    private void txtEIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEIDActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void txtLeavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLeavesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLeavesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDashboard;
    private javax.swing.JButton BtnDashboard1;
    private javax.swing.JLabel Salary;
    private javax.swing.JLabel Salary1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtDesignation;
    private javax.swing.JTextField txtEID;
    private javax.swing.JTextField txtLeaves;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtQualification;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
